# Generated by Django 5.2.1 on 2025-05-20 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etabuleiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='recomendado',
            field=models.BooleanField(default=False, help_text='Marcar como produto recomendado', verbose_name='Recomendado'),
        ),
        migrations.AlterField(
            model_name='carrinhocompras',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to=settings.AUTH_USER_MODEL),
        ),
    ]
