# Generated by Django 5.2.1 on 2025-05-23 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etabuleiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX)XXXX-XXXX ou (XX)XXXXX-XXXX', regex='^\\(\\d{2}\\)\\d{4,5}-\\d{4}$')]),
        ),
    ]
