# Generated by Django 5.2.1 on 2025-05-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etabuleiros', '0002_produto_recomendado_alter_carrinhocompras_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
