# Generated by Django 5.2.1 on 2025-05-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etabuleiros', '0002_frete_promocao_categoria_cupomdesconto_editora_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carrinhocompras',
            name='carrinho_compras_chk_1',
        ),
        migrations.AddConstraint(
            model_name='carrinhocompras',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='car_compras_chk_1'),
        ),
    ]
