# Generated by Django 5.2.1 on 2025-05-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etabuleiros', '0003_produto_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemproduto',
            name='caminho_imagem',
        ),
        migrations.AddField(
            model_name='imagemproduto',
            name='imagem',
            field=models.ImageField(default='produtos/default.jpg', upload_to='ProdImagens/'),
            preserve_default=False,
        ),
    ]
