# Generated by Django 5.2.1 on 2025-05-22 00:23

import etabuleiros.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etabuleiros', '0004_remove_imagemproduto_caminho_imagem_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', etabuleiros.models.UsuarioManager()),
            ],
        ),
    ]
